In [1]:
from __future__ import print_function
import torch

In [2]:
# Construct 5X3 matrix

x = torch.Tensor(5, 3)
print (x)


 0.0000e+00  3.6893e+19  0.0000e+00
 3.6893e+19  5.6052e-45  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  3.6893e+19  1.4799e+33
[torch.FloatTensor of size 5x3]



In [3]:
x = torch.rand(5, 3)
print (x)


 0.0984  0.0569  0.9291
 0.4217  0.9962  0.3437
 0.0558  0.8311  0.1770
 0.9416  0.4530  0.7054
 0.2766  0.6966  0.5330
[torch.FloatTensor of size 5x3]



In [4]:
# Get its size

torch.Size([5, 3])

torch.Size([5, 3])

In [5]:
#Operations

#syntax

y = torch.rand(5, 3)
print (x + y)


 0.1819  0.2456  1.6135
 1.0072  1.8422  0.3573
 0.8313  1.4468  0.7546
 1.4292  0.5205  1.1488
 0.4404  0.7253  1.2453
[torch.FloatTensor of size 5x3]



In [6]:
print (torch.add(x, y))


 0.1819  0.2456  1.6135
 1.0072  1.8422  0.3573
 0.8313  1.4468  0.7546
 1.4292  0.5205  1.1488
 0.4404  0.7253  1.2453
[torch.FloatTensor of size 5x3]



In [7]:
#giving an output tensor

result = torch.Tensor(5, 3)
torch.add(x, y, out = result)
print (result)


 0.1819  0.2456  1.6135
 1.0072  1.8422  0.3573
 0.8313  1.4468  0.7546
 1.4292  0.5205  1.1488
 0.4404  0.7253  1.2453
[torch.FloatTensor of size 5x3]



In [8]:
#in-place

y.add(x)
print (y)


 0.0835  0.1887  0.6845
 0.5855  0.8460  0.0135
 0.7755  0.6157  0.5776
 0.4876  0.0674  0.4434
 0.1638  0.0288  0.7123
[torch.FloatTensor of size 5x3]



In [9]:
print (x[:, 1])


 0.0569
 0.9962
 0.8311
 0.4530
 0.6966
[torch.FloatTensor of size 5]



In [10]:
#Converting torch Tensor to numpy Array

a = torch.ones(5)
print (a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [11]:
b = a.numpy()
print (b)

[ 1.  1.  1.  1.  1.]


In [12]:
a.add_(1)
print (a)
print (b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [16]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)

np.add(a, 1, out = a)
print (a)
print (b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]

